/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SegmentsRouteImport } from './routes/segments'
import { Route as JarvisRouteImport } from './routes/jarvis'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as ChannelRouteImport } from './routes/channel'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns.index'
import { Route as CampaignsNewRouteImport } from './routes/campaigns.new'
import { Route as CampaignsIdRouteImport } from './routes/campaigns.$id'
import { Route as ApiSettingsRouteImport } from './routes/api/settings'
import { Route as ApiSegmentsRouteImport } from './routes/api/segments'
import { Route as ApiReceiptsRouteImport } from './routes/api/receipts'
import { Route as ApiNotificationsRouteImport } from './routes/api/notifications'
import { Route as ApiCustomersRouteImport } from './routes/api/customers'
import { Route as ApiCommunicationsRouteImport } from './routes/api/communications'
import { Route as ApiCampaignsRouteImport } from './routes/api/campaigns'
import { Route as ApiSegmentsPreviewRouteImport } from './routes/api/segments.preview'
import { Route as ApiNotificationsMarkAllReadRouteImport } from './routes/api/notifications.mark-all-read'
import { Route as ApiNotificationsIdRouteImport } from './routes/api/notifications.$id'
import { Route as ApiCustomersIdRouteImport } from './routes/api/customers.$id'
import { Route as ApiCampaignsIdRouteImport } from './routes/api/campaigns.$id'
import { Route as ApiAnalyticsSuggestionsRouteImport } from './routes/api/analytics.suggestions'
import { Route as ApiAnalyticsRevenueWeeklyRouteImport } from './routes/api/analytics.revenue-weekly'
import { Route as ApiAnalyticsOverviewRouteImport } from './routes/api/analytics.overview'
import { Route as ApiAnalyticsLifecycleRouteImport } from './routes/api/analytics.lifecycle'
import { Route as ApiAnalyticsEngagementRouteImport } from './routes/api/analytics.engagement'
import { Route as ApiAnalyticsChannelsRouteImport } from './routes/api/analytics.channels'
import { Route as ApiAiSegmentRouteImport } from './routes/api/ai.segment'
import { Route as ApiAiRecommendRouteImport } from './routes/api/ai.recommend'
import { Route as ApiAiExplainRouteImport } from './routes/api/ai.explain'
import { Route as ApiCustomersIdOrdersRouteImport } from './routes/api/customers.$id.orders'
import { Route as ApiCustomersIdInsightRouteImport } from './routes/api/customers.$id.insight'
import { Route as ApiCustomersIdExplanationRouteImport } from './routes/api/customers.$id.explanation'
import { Route as ApiCampaignsIdPostmortemRouteImport } from './routes/api/campaigns.$id.postmortem'
import { Route as ApiCampaignsIdLaunchRouteImport } from './routes/api/campaigns.$id.launch'
import { Route as ApiCampaignsIdAnalysisRouteImport } from './routes/api/campaigns.$id.analysis'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentsRoute = SegmentsRouteImport.update({
  id: '/segments',
  path: '/segments',
  getParentRoute: () => rootRouteImport,
} as any)
const JarvisRoute = JarvisRouteImport.update({
  id: '/jarvis',
  path: '/jarvis',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelRoute = ChannelRouteImport.update({
  id: '/channel',
  path: '/channel',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsNewRoute = CampaignsNewRouteImport.update({
  id: '/campaigns/new',
  path: '/campaigns/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIdRoute = CampaignsIdRouteImport.update({
  id: '/campaigns/$id',
  path: '/campaigns/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsRoute = ApiSettingsRouteImport.update({
  id: '/api/settings',
  path: '/api/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSegmentsRoute = ApiSegmentsRouteImport.update({
  id: '/api/segments',
  path: '/api/segments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReceiptsRoute = ApiReceiptsRouteImport.update({
  id: '/api/receipts',
  path: '/api/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsRoute = ApiNotificationsRouteImport.update({
  id: '/api/notifications',
  path: '/api/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCustomersRoute = ApiCustomersRouteImport.update({
  id: '/api/customers',
  path: '/api/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommunicationsRoute = ApiCommunicationsRouteImport.update({
  id: '/api/communications',
  path: '/api/communications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCampaignsRoute = ApiCampaignsRouteImport.update({
  id: '/api/campaigns',
  path: '/api/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSegmentsPreviewRoute = ApiSegmentsPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => ApiSegmentsRoute,
} as any)
const ApiNotificationsMarkAllReadRoute =
  ApiNotificationsMarkAllReadRouteImport.update({
    id: '/mark-all-read',
    path: '/mark-all-read',
    getParentRoute: () => ApiNotificationsRoute,
  } as any)
const ApiNotificationsIdRoute = ApiNotificationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiNotificationsRoute,
} as any)
const ApiCustomersIdRoute = ApiCustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiCustomersRoute,
} as any)
const ApiCampaignsIdRoute = ApiCampaignsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiCampaignsRoute,
} as any)
const ApiAnalyticsSuggestionsRoute = ApiAnalyticsSuggestionsRouteImport.update({
  id: '/api/analytics/suggestions',
  path: '/api/analytics/suggestions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsRevenueWeeklyRoute =
  ApiAnalyticsRevenueWeeklyRouteImport.update({
    id: '/api/analytics/revenue-weekly',
    path: '/api/analytics/revenue-weekly',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAnalyticsOverviewRoute = ApiAnalyticsOverviewRouteImport.update({
  id: '/api/analytics/overview',
  path: '/api/analytics/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsLifecycleRoute = ApiAnalyticsLifecycleRouteImport.update({
  id: '/api/analytics/lifecycle',
  path: '/api/analytics/lifecycle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsEngagementRoute = ApiAnalyticsEngagementRouteImport.update({
  id: '/api/analytics/engagement',
  path: '/api/analytics/engagement',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsChannelsRoute = ApiAnalyticsChannelsRouteImport.update({
  id: '/api/analytics/channels',
  path: '/api/analytics/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiSegmentRoute = ApiAiSegmentRouteImport.update({
  id: '/api/ai/segment',
  path: '/api/ai/segment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiRecommendRoute = ApiAiRecommendRouteImport.update({
  id: '/api/ai/recommend',
  path: '/api/ai/recommend',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiExplainRoute = ApiAiExplainRouteImport.update({
  id: '/api/ai/explain',
  path: '/api/ai/explain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCustomersIdOrdersRoute = ApiCustomersIdOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ApiCustomersIdRoute,
} as any)
const ApiCustomersIdInsightRoute = ApiCustomersIdInsightRouteImport.update({
  id: '/insight',
  path: '/insight',
  getParentRoute: () => ApiCustomersIdRoute,
} as any)
const ApiCustomersIdExplanationRoute =
  ApiCustomersIdExplanationRouteImport.update({
    id: '/explanation',
    path: '/explanation',
    getParentRoute: () => ApiCustomersIdRoute,
  } as any)
const ApiCampaignsIdPostmortemRoute =
  ApiCampaignsIdPostmortemRouteImport.update({
    id: '/postmortem',
    path: '/postmortem',
    getParentRoute: () => ApiCampaignsIdRoute,
  } as any)
const ApiCampaignsIdLaunchRoute = ApiCampaignsIdLaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => ApiCampaignsIdRoute,
} as any)
const ApiCampaignsIdAnalysisRoute = ApiCampaignsIdAnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => ApiCampaignsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/channel': typeof ChannelRoute
  '/customers': typeof CustomersRoute
  '/jarvis': typeof JarvisRoute
  '/segments': typeof SegmentsRoute
  '/settings': typeof SettingsRoute
  '/api/campaigns': typeof ApiCampaignsRouteWithChildren
  '/api/communications': typeof ApiCommunicationsRoute
  '/api/customers': typeof ApiCustomersRouteWithChildren
  '/api/notifications': typeof ApiNotificationsRouteWithChildren
  '/api/receipts': typeof ApiReceiptsRoute
  '/api/segments': typeof ApiSegmentsRouteWithChildren
  '/api/settings': typeof ApiSettingsRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/api/ai/explain': typeof ApiAiExplainRoute
  '/api/ai/recommend': typeof ApiAiRecommendRoute
  '/api/ai/segment': typeof ApiAiSegmentRoute
  '/api/analytics/channels': typeof ApiAnalyticsChannelsRoute
  '/api/analytics/engagement': typeof ApiAnalyticsEngagementRoute
  '/api/analytics/lifecycle': typeof ApiAnalyticsLifecycleRoute
  '/api/analytics/overview': typeof ApiAnalyticsOverviewRoute
  '/api/analytics/revenue-weekly': typeof ApiAnalyticsRevenueWeeklyRoute
  '/api/analytics/suggestions': typeof ApiAnalyticsSuggestionsRoute
  '/api/campaigns/$id': typeof ApiCampaignsIdRouteWithChildren
  '/api/customers/$id': typeof ApiCustomersIdRouteWithChildren
  '/api/notifications/$id': typeof ApiNotificationsIdRoute
  '/api/notifications/mark-all-read': typeof ApiNotificationsMarkAllReadRoute
  '/api/segments/preview': typeof ApiSegmentsPreviewRoute
  '/api/campaigns/$id/analysis': typeof ApiCampaignsIdAnalysisRoute
  '/api/campaigns/$id/launch': typeof ApiCampaignsIdLaunchRoute
  '/api/campaigns/$id/postmortem': typeof ApiCampaignsIdPostmortemRoute
  '/api/customers/$id/explanation': typeof ApiCustomersIdExplanationRoute
  '/api/customers/$id/insight': typeof ApiCustomersIdInsightRoute
  '/api/customers/$id/orders': typeof ApiCustomersIdOrdersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/channel': typeof ChannelRoute
  '/customers': typeof CustomersRoute
  '/jarvis': typeof JarvisRoute
  '/segments': typeof SegmentsRoute
  '/settings': typeof SettingsRoute
  '/api/campaigns': typeof ApiCampaignsRouteWithChildren
  '/api/communications': typeof ApiCommunicationsRoute
  '/api/customers': typeof ApiCustomersRouteWithChildren
  '/api/notifications': typeof ApiNotificationsRouteWithChildren
  '/api/receipts': typeof ApiReceiptsRoute
  '/api/segments': typeof ApiSegmentsRouteWithChildren
  '/api/settings': typeof ApiSettingsRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/api/ai/explain': typeof ApiAiExplainRoute
  '/api/ai/recommend': typeof ApiAiRecommendRoute
  '/api/ai/segment': typeof ApiAiSegmentRoute
  '/api/analytics/channels': typeof ApiAnalyticsChannelsRoute
  '/api/analytics/engagement': typeof ApiAnalyticsEngagementRoute
  '/api/analytics/lifecycle': typeof ApiAnalyticsLifecycleRoute
  '/api/analytics/overview': typeof ApiAnalyticsOverviewRoute
  '/api/analytics/revenue-weekly': typeof ApiAnalyticsRevenueWeeklyRoute
  '/api/analytics/suggestions': typeof ApiAnalyticsSuggestionsRoute
  '/api/campaigns/$id': typeof ApiCampaignsIdRouteWithChildren
  '/api/customers/$id': typeof ApiCustomersIdRouteWithChildren
  '/api/notifications/$id': typeof ApiNotificationsIdRoute
  '/api/notifications/mark-all-read': typeof ApiNotificationsMarkAllReadRoute
  '/api/segments/preview': typeof ApiSegmentsPreviewRoute
  '/api/campaigns/$id/analysis': typeof ApiCampaignsIdAnalysisRoute
  '/api/campaigns/$id/launch': typeof ApiCampaignsIdLaunchRoute
  '/api/campaigns/$id/postmortem': typeof ApiCampaignsIdPostmortemRoute
  '/api/customers/$id/explanation': typeof ApiCustomersIdExplanationRoute
  '/api/customers/$id/insight': typeof ApiCustomersIdInsightRoute
  '/api/customers/$id/orders': typeof ApiCustomersIdOrdersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/channel': typeof ChannelRoute
  '/customers': typeof CustomersRoute
  '/jarvis': typeof JarvisRoute
  '/segments': typeof SegmentsRoute
  '/settings': typeof SettingsRoute
  '/api/campaigns': typeof ApiCampaignsRouteWithChildren
  '/api/communications': typeof ApiCommunicationsRoute
  '/api/customers': typeof ApiCustomersRouteWithChildren
  '/api/notifications': typeof ApiNotificationsRouteWithChildren
  '/api/receipts': typeof ApiReceiptsRoute
  '/api/segments': typeof ApiSegmentsRouteWithChildren
  '/api/settings': typeof ApiSettingsRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/api/ai/explain': typeof ApiAiExplainRoute
  '/api/ai/recommend': typeof ApiAiRecommendRoute
  '/api/ai/segment': typeof ApiAiSegmentRoute
  '/api/analytics/channels': typeof ApiAnalyticsChannelsRoute
  '/api/analytics/engagement': typeof ApiAnalyticsEngagementRoute
  '/api/analytics/lifecycle': typeof ApiAnalyticsLifecycleRoute
  '/api/analytics/overview': typeof ApiAnalyticsOverviewRoute
  '/api/analytics/revenue-weekly': typeof ApiAnalyticsRevenueWeeklyRoute
  '/api/analytics/suggestions': typeof ApiAnalyticsSuggestionsRoute
  '/api/campaigns/$id': typeof ApiCampaignsIdRouteWithChildren
  '/api/customers/$id': typeof ApiCustomersIdRouteWithChildren
  '/api/notifications/$id': typeof ApiNotificationsIdRoute
  '/api/notifications/mark-all-read': typeof ApiNotificationsMarkAllReadRoute
  '/api/segments/preview': typeof ApiSegmentsPreviewRoute
  '/api/campaigns/$id/analysis': typeof ApiCampaignsIdAnalysisRoute
  '/api/campaigns/$id/launch': typeof ApiCampaignsIdLaunchRoute
  '/api/campaigns/$id/postmortem': typeof ApiCampaignsIdPostmortemRoute
  '/api/customers/$id/explanation': typeof ApiCustomersIdExplanationRoute
  '/api/customers/$id/insight': typeof ApiCustomersIdInsightRoute
  '/api/customers/$id/orders': typeof ApiCustomersIdOrdersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/channel'
    | '/customers'
    | '/jarvis'
    | '/segments'
    | '/settings'
    | '/api/campaigns'
    | '/api/communications'
    | '/api/customers'
    | '/api/notifications'
    | '/api/receipts'
    | '/api/segments'
    | '/api/settings'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/campaigns/'
    | '/api/ai/explain'
    | '/api/ai/recommend'
    | '/api/ai/segment'
    | '/api/analytics/channels'
    | '/api/analytics/engagement'
    | '/api/analytics/lifecycle'
    | '/api/analytics/overview'
    | '/api/analytics/revenue-weekly'
    | '/api/analytics/suggestions'
    | '/api/campaigns/$id'
    | '/api/customers/$id'
    | '/api/notifications/$id'
    | '/api/notifications/mark-all-read'
    | '/api/segments/preview'
    | '/api/campaigns/$id/analysis'
    | '/api/campaigns/$id/launch'
    | '/api/campaigns/$id/postmortem'
    | '/api/customers/$id/explanation'
    | '/api/customers/$id/insight'
    | '/api/customers/$id/orders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/channel'
    | '/customers'
    | '/jarvis'
    | '/segments'
    | '/settings'
    | '/api/campaigns'
    | '/api/communications'
    | '/api/customers'
    | '/api/notifications'
    | '/api/receipts'
    | '/api/segments'
    | '/api/settings'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/campaigns'
    | '/api/ai/explain'
    | '/api/ai/recommend'
    | '/api/ai/segment'
    | '/api/analytics/channels'
    | '/api/analytics/engagement'
    | '/api/analytics/lifecycle'
    | '/api/analytics/overview'
    | '/api/analytics/revenue-weekly'
    | '/api/analytics/suggestions'
    | '/api/campaigns/$id'
    | '/api/customers/$id'
    | '/api/notifications/$id'
    | '/api/notifications/mark-all-read'
    | '/api/segments/preview'
    | '/api/campaigns/$id/analysis'
    | '/api/campaigns/$id/launch'
    | '/api/campaigns/$id/postmortem'
    | '/api/customers/$id/explanation'
    | '/api/customers/$id/insight'
    | '/api/customers/$id/orders'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/channel'
    | '/customers'
    | '/jarvis'
    | '/segments'
    | '/settings'
    | '/api/campaigns'
    | '/api/communications'
    | '/api/customers'
    | '/api/notifications'
    | '/api/receipts'
    | '/api/segments'
    | '/api/settings'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/campaigns/'
    | '/api/ai/explain'
    | '/api/ai/recommend'
    | '/api/ai/segment'
    | '/api/analytics/channels'
    | '/api/analytics/engagement'
    | '/api/analytics/lifecycle'
    | '/api/analytics/overview'
    | '/api/analytics/revenue-weekly'
    | '/api/analytics/suggestions'
    | '/api/campaigns/$id'
    | '/api/customers/$id'
    | '/api/notifications/$id'
    | '/api/notifications/mark-all-read'
    | '/api/segments/preview'
    | '/api/campaigns/$id/analysis'
    | '/api/campaigns/$id/launch'
    | '/api/campaigns/$id/postmortem'
    | '/api/customers/$id/explanation'
    | '/api/customers/$id/insight'
    | '/api/customers/$id/orders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ChannelRoute: typeof ChannelRoute
  CustomersRoute: typeof CustomersRoute
  JarvisRoute: typeof JarvisRoute
  SegmentsRoute: typeof SegmentsRoute
  SettingsRoute: typeof SettingsRoute
  ApiCampaignsRoute: typeof ApiCampaignsRouteWithChildren
  ApiCommunicationsRoute: typeof ApiCommunicationsRoute
  ApiCustomersRoute: typeof ApiCustomersRouteWithChildren
  ApiNotificationsRoute: typeof ApiNotificationsRouteWithChildren
  ApiReceiptsRoute: typeof ApiReceiptsRoute
  ApiSegmentsRoute: typeof ApiSegmentsRouteWithChildren
  ApiSettingsRoute: typeof ApiSettingsRoute
  CampaignsIdRoute: typeof CampaignsIdRoute
  CampaignsNewRoute: typeof CampaignsNewRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
  ApiAiExplainRoute: typeof ApiAiExplainRoute
  ApiAiRecommendRoute: typeof ApiAiRecommendRoute
  ApiAiSegmentRoute: typeof ApiAiSegmentRoute
  ApiAnalyticsChannelsRoute: typeof ApiAnalyticsChannelsRoute
  ApiAnalyticsEngagementRoute: typeof ApiAnalyticsEngagementRoute
  ApiAnalyticsLifecycleRoute: typeof ApiAnalyticsLifecycleRoute
  ApiAnalyticsOverviewRoute: typeof ApiAnalyticsOverviewRoute
  ApiAnalyticsRevenueWeeklyRoute: typeof ApiAnalyticsRevenueWeeklyRoute
  ApiAnalyticsSuggestionsRoute: typeof ApiAnalyticsSuggestionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segments': {
      id: '/segments'
      path: '/segments'
      fullPath: '/segments'
      preLoaderRoute: typeof SegmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jarvis': {
      id: '/jarvis'
      path: '/jarvis'
      fullPath: '/jarvis'
      preLoaderRoute: typeof JarvisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel': {
      id: '/channel'
      path: '/channel'
      fullPath: '/channel'
      preLoaderRoute: typeof ChannelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/new': {
      id: '/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof CampaignsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$id': {
      id: '/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof CampaignsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings': {
      id: '/api/settings'
      path: '/api/settings'
      fullPath: '/api/settings'
      preLoaderRoute: typeof ApiSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/segments': {
      id: '/api/segments'
      path: '/api/segments'
      fullPath: '/api/segments'
      preLoaderRoute: typeof ApiSegmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/receipts': {
      id: '/api/receipts'
      path: '/api/receipts'
      fullPath: '/api/receipts'
      preLoaderRoute: typeof ApiReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications': {
      id: '/api/notifications'
      path: '/api/notifications'
      fullPath: '/api/notifications'
      preLoaderRoute: typeof ApiNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customers': {
      id: '/api/customers'
      path: '/api/customers'
      fullPath: '/api/customers'
      preLoaderRoute: typeof ApiCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/communications': {
      id: '/api/communications'
      path: '/api/communications'
      fullPath: '/api/communications'
      preLoaderRoute: typeof ApiCommunicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/campaigns': {
      id: '/api/campaigns'
      path: '/api/campaigns'
      fullPath: '/api/campaigns'
      preLoaderRoute: typeof ApiCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/segments/preview': {
      id: '/api/segments/preview'
      path: '/preview'
      fullPath: '/api/segments/preview'
      preLoaderRoute: typeof ApiSegmentsPreviewRouteImport
      parentRoute: typeof ApiSegmentsRoute
    }
    '/api/notifications/mark-all-read': {
      id: '/api/notifications/mark-all-read'
      path: '/mark-all-read'
      fullPath: '/api/notifications/mark-all-read'
      preLoaderRoute: typeof ApiNotificationsMarkAllReadRouteImport
      parentRoute: typeof ApiNotificationsRoute
    }
    '/api/notifications/$id': {
      id: '/api/notifications/$id'
      path: '/$id'
      fullPath: '/api/notifications/$id'
      preLoaderRoute: typeof ApiNotificationsIdRouteImport
      parentRoute: typeof ApiNotificationsRoute
    }
    '/api/customers/$id': {
      id: '/api/customers/$id'
      path: '/$id'
      fullPath: '/api/customers/$id'
      preLoaderRoute: typeof ApiCustomersIdRouteImport
      parentRoute: typeof ApiCustomersRoute
    }
    '/api/campaigns/$id': {
      id: '/api/campaigns/$id'
      path: '/$id'
      fullPath: '/api/campaigns/$id'
      preLoaderRoute: typeof ApiCampaignsIdRouteImport
      parentRoute: typeof ApiCampaignsRoute
    }
    '/api/analytics/suggestions': {
      id: '/api/analytics/suggestions'
      path: '/api/analytics/suggestions'
      fullPath: '/api/analytics/suggestions'
      preLoaderRoute: typeof ApiAnalyticsSuggestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics/revenue-weekly': {
      id: '/api/analytics/revenue-weekly'
      path: '/api/analytics/revenue-weekly'
      fullPath: '/api/analytics/revenue-weekly'
      preLoaderRoute: typeof ApiAnalyticsRevenueWeeklyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics/overview': {
      id: '/api/analytics/overview'
      path: '/api/analytics/overview'
      fullPath: '/api/analytics/overview'
      preLoaderRoute: typeof ApiAnalyticsOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics/lifecycle': {
      id: '/api/analytics/lifecycle'
      path: '/api/analytics/lifecycle'
      fullPath: '/api/analytics/lifecycle'
      preLoaderRoute: typeof ApiAnalyticsLifecycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics/engagement': {
      id: '/api/analytics/engagement'
      path: '/api/analytics/engagement'
      fullPath: '/api/analytics/engagement'
      preLoaderRoute: typeof ApiAnalyticsEngagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics/channels': {
      id: '/api/analytics/channels'
      path: '/api/analytics/channels'
      fullPath: '/api/analytics/channels'
      preLoaderRoute: typeof ApiAnalyticsChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/segment': {
      id: '/api/ai/segment'
      path: '/api/ai/segment'
      fullPath: '/api/ai/segment'
      preLoaderRoute: typeof ApiAiSegmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/recommend': {
      id: '/api/ai/recommend'
      path: '/api/ai/recommend'
      fullPath: '/api/ai/recommend'
      preLoaderRoute: typeof ApiAiRecommendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/explain': {
      id: '/api/ai/explain'
      path: '/api/ai/explain'
      fullPath: '/api/ai/explain'
      preLoaderRoute: typeof ApiAiExplainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customers/$id/orders': {
      id: '/api/customers/$id/orders'
      path: '/orders'
      fullPath: '/api/customers/$id/orders'
      preLoaderRoute: typeof ApiCustomersIdOrdersRouteImport
      parentRoute: typeof ApiCustomersIdRoute
    }
    '/api/customers/$id/insight': {
      id: '/api/customers/$id/insight'
      path: '/insight'
      fullPath: '/api/customers/$id/insight'
      preLoaderRoute: typeof ApiCustomersIdInsightRouteImport
      parentRoute: typeof ApiCustomersIdRoute
    }
    '/api/customers/$id/explanation': {
      id: '/api/customers/$id/explanation'
      path: '/explanation'
      fullPath: '/api/customers/$id/explanation'
      preLoaderRoute: typeof ApiCustomersIdExplanationRouteImport
      parentRoute: typeof ApiCustomersIdRoute
    }
    '/api/campaigns/$id/postmortem': {
      id: '/api/campaigns/$id/postmortem'
      path: '/postmortem'
      fullPath: '/api/campaigns/$id/postmortem'
      preLoaderRoute: typeof ApiCampaignsIdPostmortemRouteImport
      parentRoute: typeof ApiCampaignsIdRoute
    }
    '/api/campaigns/$id/launch': {
      id: '/api/campaigns/$id/launch'
      path: '/launch'
      fullPath: '/api/campaigns/$id/launch'
      preLoaderRoute: typeof ApiCampaignsIdLaunchRouteImport
      parentRoute: typeof ApiCampaignsIdRoute
    }
    '/api/campaigns/$id/analysis': {
      id: '/api/campaigns/$id/analysis'
      path: '/analysis'
      fullPath: '/api/campaigns/$id/analysis'
      preLoaderRoute: typeof ApiCampaignsIdAnalysisRouteImport
      parentRoute: typeof ApiCampaignsIdRoute
    }
  }
}

interface ApiCampaignsIdRouteChildren {
  ApiCampaignsIdAnalysisRoute: typeof ApiCampaignsIdAnalysisRoute
  ApiCampaignsIdLaunchRoute: typeof ApiCampaignsIdLaunchRoute
  ApiCampaignsIdPostmortemRoute: typeof ApiCampaignsIdPostmortemRoute
}

const ApiCampaignsIdRouteChildren: ApiCampaignsIdRouteChildren = {
  ApiCampaignsIdAnalysisRoute: ApiCampaignsIdAnalysisRoute,
  ApiCampaignsIdLaunchRoute: ApiCampaignsIdLaunchRoute,
  ApiCampaignsIdPostmortemRoute: ApiCampaignsIdPostmortemRoute,
}

const ApiCampaignsIdRouteWithChildren = ApiCampaignsIdRoute._addFileChildren(
  ApiCampaignsIdRouteChildren,
)

interface ApiCampaignsRouteChildren {
  ApiCampaignsIdRoute: typeof ApiCampaignsIdRouteWithChildren
}

const ApiCampaignsRouteChildren: ApiCampaignsRouteChildren = {
  ApiCampaignsIdRoute: ApiCampaignsIdRouteWithChildren,
}

const ApiCampaignsRouteWithChildren = ApiCampaignsRoute._addFileChildren(
  ApiCampaignsRouteChildren,
)

interface ApiCustomersIdRouteChildren {
  ApiCustomersIdExplanationRoute: typeof ApiCustomersIdExplanationRoute
  ApiCustomersIdInsightRoute: typeof ApiCustomersIdInsightRoute
  ApiCustomersIdOrdersRoute: typeof ApiCustomersIdOrdersRoute
}

const ApiCustomersIdRouteChildren: ApiCustomersIdRouteChildren = {
  ApiCustomersIdExplanationRoute: ApiCustomersIdExplanationRoute,
  ApiCustomersIdInsightRoute: ApiCustomersIdInsightRoute,
  ApiCustomersIdOrdersRoute: ApiCustomersIdOrdersRoute,
}

const ApiCustomersIdRouteWithChildren = ApiCustomersIdRoute._addFileChildren(
  ApiCustomersIdRouteChildren,
)

interface ApiCustomersRouteChildren {
  ApiCustomersIdRoute: typeof ApiCustomersIdRouteWithChildren
}

const ApiCustomersRouteChildren: ApiCustomersRouteChildren = {
  ApiCustomersIdRoute: ApiCustomersIdRouteWithChildren,
}

const ApiCustomersRouteWithChildren = ApiCustomersRoute._addFileChildren(
  ApiCustomersRouteChildren,
)

interface ApiNotificationsRouteChildren {
  ApiNotificationsIdRoute: typeof ApiNotificationsIdRoute
  ApiNotificationsMarkAllReadRoute: typeof ApiNotificationsMarkAllReadRoute
}

const ApiNotificationsRouteChildren: ApiNotificationsRouteChildren = {
  ApiNotificationsIdRoute: ApiNotificationsIdRoute,
  ApiNotificationsMarkAllReadRoute: ApiNotificationsMarkAllReadRoute,
}

const ApiNotificationsRouteWithChildren =
  ApiNotificationsRoute._addFileChildren(ApiNotificationsRouteChildren)

interface ApiSegmentsRouteChildren {
  ApiSegmentsPreviewRoute: typeof ApiSegmentsPreviewRoute
}

const ApiSegmentsRouteChildren: ApiSegmentsRouteChildren = {
  ApiSegmentsPreviewRoute: ApiSegmentsPreviewRoute,
}

const ApiSegmentsRouteWithChildren = ApiSegmentsRoute._addFileChildren(
  ApiSegmentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  ChannelRoute: ChannelRoute,
  CustomersRoute: CustomersRoute,
  JarvisRoute: JarvisRoute,
  SegmentsRoute: SegmentsRoute,
  SettingsRoute: SettingsRoute,
  ApiCampaignsRoute: ApiCampaignsRouteWithChildren,
  ApiCommunicationsRoute: ApiCommunicationsRoute,
  ApiCustomersRoute: ApiCustomersRouteWithChildren,
  ApiNotificationsRoute: ApiNotificationsRouteWithChildren,
  ApiReceiptsRoute: ApiReceiptsRoute,
  ApiSegmentsRoute: ApiSegmentsRouteWithChildren,
  ApiSettingsRoute: ApiSettingsRoute,
  CampaignsIdRoute: CampaignsIdRoute,
  CampaignsNewRoute: CampaignsNewRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
  ApiAiExplainRoute: ApiAiExplainRoute,
  ApiAiRecommendRoute: ApiAiRecommendRoute,
  ApiAiSegmentRoute: ApiAiSegmentRoute,
  ApiAnalyticsChannelsRoute: ApiAnalyticsChannelsRoute,
  ApiAnalyticsEngagementRoute: ApiAnalyticsEngagementRoute,
  ApiAnalyticsLifecycleRoute: ApiAnalyticsLifecycleRoute,
  ApiAnalyticsOverviewRoute: ApiAnalyticsOverviewRoute,
  ApiAnalyticsRevenueWeeklyRoute: ApiAnalyticsRevenueWeeklyRoute,
  ApiAnalyticsSuggestionsRoute: ApiAnalyticsSuggestionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
